baseURL = 'http://www.fieldside.net'
languageCode = 'ja-jp'
title = 'fieldside.net'
theme = "tella"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  mainSections = ['blog']

  [params.logo]
    main = "img/logo/logo.jpeg"
    alt = "fieldside"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "fieldside.net"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fa5 = true

  [params.homepage_meta_tags]
    meta_description = "fieldside corporate site"
    meta_og_title = "fieldside.net"
    meta_og_type = "website"
    meta_og_url = "https://www.fieldside.net"
    meta_og_image = ""
    meta_og_description = "fieldside corporate site"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
